pipeline {
    agent any
    environment {
        DOCKER_HUB_CREDENTIALS = 'dockerhub-creds' 
        IMAGE_NAME = 'username/sample-app'
        PORT = '5000'
    }
    stages {
        stage('Clone Repo') {
            steps {
                git branch: 'main', url: 'https://github.com/poorna484/docker_project.git'
            }
        }

        stage('Build & Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', "${DOCKER_HUB_CREDENTIALS}") {
                        def app = docker.build("${IMAGE_NAME}:${env.BUILD_NUMBER}")
                        app.push()         // Push build number tag
                        app.push('latest') // Optional: push latest tag
                        echo "Docker image pushed successfully"
                    }
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    sh "docker rm -f sample-app || true"  // Remove old container
                    docker.image("${IMAGE_NAME}:${env.BUILD_NUMBER}").run("-d -p ${PORT}:${PORT} --name sample-app")
                }
            }
        }
    }
    post {
        always {
            echo 'Pipeline Finished'
        }
    }
}
